version: '3.8'
services:
  pg_master:
    image: postgres:16.3
    container_name: pg_master
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tsf_api
    volumes:
      - pg_master_data:/var/lib/postgresql/data
    networks:
      - tsf_network
    ports:
      - 5433:5432

volumes:
  pg_master_data:

networks:
  tsf_network:
    driver: bridge
    name: tsf_network